name: Run Robot Framework Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  robot-tests:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run Robot Framework tests
      run: |
        robot tests/
    
    - name: Run Robot Framework tests with output
      run: |
        mkdir results
        robot --output results/output.xml --report results/report.html --log results/log.html tests/

    - name: Upload test report
      uses: actions/upload-artifact@v4
      with:
        name: robot-test-report
        path: results/

